theme: jekyll-theme-minimal

title: Claire Najjuuko
# logo: /assets/img/headshot_circle.png
logo: ClaireProfilePhoto.jpg
description: Data Science Ph.D student
show_downloads: true

cv_url: Claire_Najjuuko_CV_Oct2025.pdf

[View My CV](Claire_Najjuuko_CV_Oct2025.pdf)  
[Google Scholar](https://scholar.google.com/citations?user=ClaireNajjuuko)

# email: c.najjuuko@wustl.edu
# googlescholar: "https://scholar.google.com/citations?user=ClaireNajjuuko"
# linkedin: "https://www.linkedin.com/in/claire-najjuuko-9131a5377/"

social:
    links:
    # first element serves as the copyright owner's link
    - https://github.com/cgoldberg
    - https://www.linkedin.com/in/cgoldberg
    # uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://twitter.com/username
