title: Claire Najjuuko
# logo: /assets/img/headshot_circle.png
logo: ClaireProfilePhoto.jpg
description: Data Science Ph.D student
#show_downloads: true

email: c.najjuuko@wustl.edu
googlescholar: "https://scholar.google.com/citations?user=ClaireNajjuuko"
linkedin: "https://www.linkedin.com/in/claire-najjuuko-9131a5377/"

theme: jekyll-theme-minimal


# [View My CV](Claire Najjuuko CV_Mar2025.pdf)  
# [Google Scholar](https://scholar.google.com/citations?user=ClaireNajjuuko)
