title: Claire Najjuuko
email: "c.najjuuko@wustl.edu"
# logo: /assets/img/headshot_circle.png
logo: ClaireProfilePhoto.jpg
description: Data Science Ph.D student
#show_downloads: true
theme: jekyll-theme-minimal-mistakes

# email: c.najjuuko@wustl.edu
# googlescholar: "https://scholar.google.com/citations?user=ClaireNajjuuko"
# linkedin: "https://www.linkedin.com/in/claire-najjuuko-9131a5377/"




# [View My CV](Claire Najjuuko CV_Mar2025.pdf)  
# [Google Scholar](https://scholar.google.com/citations?user=ClaireNajjuuko)
